### ISSUE TITLE
Doesn't support custom user models in Django 1.5 

### ISSUE THREAD

**Issue by ravishivt** [miratcan/qhonuskan-votes#14]
Django 1.5 allows custom user models.  This package specifically references django.contrib.auth.models.User model which will fail when using a custom model.

This can be fixed by doing this after the import block of qhonuskan_votes/models.py:

``` python
# Support Django 1.5's custom user models
try:
    from django.contrib.auth import get_user_model
except ImportError:
    get_user_model = lambda: User
```

And then changing the "voter" line in the same models.py file:

``` python
voter = models.ForeignKey(
                User,
                verbose_name=_('voter'))
```

to:

``` python
voter = models.ForeignKey(
                get_user_model(),
                verbose_name=_('voter'))
```

I'm new to GitHub and I don't know how to post file diffs.  Pointers appreciated.  :)

**Comment by miratcan** [comment]
This Project accepts [Octotreats](https://octotreat.com). You may promise the owner a treat upon completion of this Issue [here](https://octotreat.com/projects/12/treats/new?issue_id=37)

**Comment by miratcan** [comment]
Thanks!
