### ISSUE TITLE
vote_score not working on a list page

### ISSUE THREAD

**Issue by mal3x** [miratcan/qhonuskan-votes#20]
I have a problem with showing the vote_score on a list of objects. On the detail view, everything works fine and the score shows up correctly. On the list page I can see the marked up and down arrows, if I vote on a new it shows the correct score, but as soon as I refresh the page the displayed score goes to 0 although the score saves correctly. I saw a similar issue that was closed 9 months ago. 

even if I try to output just the score with {{ object.vote_score }} in the loop it returns an empty value although everything else works fine.

Should I do something different on a list view?

**Comment by miratcan** [comment]
This Project accepts [Octotreats](https://octotreat.com). You may promise the owner a treat upon completion of this Issue [here](https://octotreat.com/projects/12/treats/new?issue_id=36)

**Comment by miratcan** [comment]
Is this problem solved?
