### ISSUE TITLE
AttributeError: type object 'Thing' has no attribute 'objects'

### ISSUE THREAD

**Issue by nickb4** [miratcan/qhonuskan-votes#8]
Hi,

I believe that I have configured my project according to your tutorial and demo project, but I am encountering an error: 

```
AttributeError: type object 'Thing' has no attribute 'objects'
```

which references a call in my view to: 

```
Thing.objects.all()
```

This error **only** occurs when the qhonuskan_votes 'VotesField' and 'ObjectsWithScoresManager' fields are included in my model `Thing`:

```
class Thing(models.Model):
    user = models.ForeignKey(User)
    color = models.CharField(max_length=5, choices=COLORS)
    photo = models.ImageField(upload_to='photos')
    make = models.ForeignKey('Make')
    additional_description = models.TextField(default='')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    votes = VotesField()
    objects_with_scores = ObjectsWithScoresManager()

    def __unicode__(self):
        return unicode(self.user)

@receiver(vote_changed)
def my_callback(sender, dispatch_uid="vote_changed", **kwargs):
    print "vote_changed signal fired."
```

I believe that I set up my template properly, as well:

```
{% extends 'base.html' %}
{% load qhonuskan_votes static %}
{% get_static_prefix as STATIC_PREFIX %}

<head>
<link href="{{STATIC_PREFIX}}default_buttons.css" rel="stylesheet" type="text/css" />
<style type="text/css">
div.vote_buttons {
   width: 40px;
   margin-right: 5px;
   float: left;
   border: 1px solid #666;
 }
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
{% voting_script %}
</head>

{% for thing in things %}
<div class="object">
    {% vote_buttons_for thing %}
      <div class="text">
        {{ thing.additional_description }}
      </div>
</div>
{% endfor %}
```

In the view I am trying to call `Thing.objects.all()` to use in a different part of the template, but including the `VotesField` and `ObjectsWithScoresManager` in my model for Thing results in the AttributeError described above. 

Am I doing something wrong in my use of the app? Perhaps, do I need to create a separate model `Vote` Then reference its relation to `Thing` by using a FK? 

Thanks for any clarification on this issue!

**Comment by miratcan** [comment]
This Project accepts [Octotreats](https://octotreat.com). You may promise the owner a treat upon completion of this Issue [here](https://octotreat.com/projects/12/treats/new?issue_id=39)
